import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Footer, Header } from "@/components";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Bouquet Corporate Voucher",
  description: "Generated by create next app",
};

const generalSans = localFont({
  src: "./fonts/GeneralSans-Variable.ttf",
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />
        <main
          className={cn(
            "antialiased max-w-screen overflow-x-hidden relative font-sans",
            generalSans.variable
          )}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
